const emotidex = [
  {
    id: 1,
    emoji: "😀",
    name: "Grinning Face",
    meaning: "A yellow face with simple, open eyes and a broad, open smile, showing upper teeth and tongue on some platforms. Often conveys general pleasure and good cheer or humor.",
  },
     { id: 2,
       emoji: "😄",
      name: "Grinning Face with Smiling Eyes",
      meaning:"A yellow face with smiling eyes and a broad, open smile, showing upper teeth and tongue on some platforms. Often conveys general happiness and good-natured amusement.",
},
    {  id: 3,
      emoji: "😆",
      name: "Grinning Squinting Face",
      meaning:"A yellow face with a broad, open smile and scrunched, X-shaped eyes. Often conveys excitement or hearty laughter.",
  },
    {id: 4,
      emoji: "😅",
      name: "Grinning Face with Sweat",
      meaning:"Has the same grin and eyes as 😄 Grinning Face With Smiling Eyes but with a single, blue bead of sweat, usually over its left eye. Intended to depict nerves or discomfort but commonly used to express a close call, as if saying Whew! and wiping sweat from the forehead.",
  },
  {  id: 5,
    emoji:  "🤣",
      name: "Rolling on the Floor Laughing",
      meaning:"A yellow face with a big grin and scrunched, X-shaped eyes, tilted on its side as if rolling on the floor laughing (the internet acronym ROFL). Sheds two tears and tilts right on most platforms. Often conveys hysterical laughter more intense than 😂 Face With Tears of Joy.",
  },
  { id: 6, 
    emoji:  "😂",
      name: "Face with Tears of Joy",
      meaning:"A yellow face with a big grin, uplifted eyebrows, and smiling eyes, each shedding a tear from laughing so hard. Widely used to show something is funny or pleasing. ",
    },
    { id: 7,
      emoji:  "😒",
      name: "Unamused Face",
      meaning:"A yellow face with slightly raised eyebrows, a frown, and eyes looking to the side. May convey a variety of negative emotions, including irritation, displeasure, grumpiness, and skepticism, as if giving the side-eye.",
  },
  { id: 8, 
    emoji:  "🙃",
      name: "Upside-Down Face",
      meaning:"A classic smiley, turned upside down. Implemented as a flipped version of 🙂 Slightly Smiling Face on most platforms. Commonly used to convey irony, sarcasm, joking, or a sense of goofiness or silliness. Its intent can be similar to the bemused Oh well! of 🤷 Person Shrugging or the shruggie emoticon, ¯\\_(ツ)_/¯.",
    },
   { id: 9,
     emoji:  "😉",
      name: "Winking Face",
      meaning:"A yellow face with a slight smile shown winking, usually its left eye. May signal a joke, flirtation, hidden meaning, or general positivity. Tone varies, including playful, affectionate, suggestive, or ironic.",
    },
    {id: 10,
      emoji:  "🙄",
      name: "Face with Rolling Eyes",
      meaning:"A yellow face with a small, closed mouth, flat or frowning, rolling its large, white eyes upwards. As with the gesture of an eye-roll, commonly conveys moderate disdain, disapproval, frustration, or boredom. Tone varies, including playful, sassy, resentful, and sarcastic, as if saying Yeah, whatever.",
    },
    {id: 11,
      emoji:  "😇",
      name: "Smiling Face with Halo",
      meaning:"A yellow face with smiling eyes, closed smile, and halo, usually blue, overhead. Often represents angels, prayers, and blessings. May also convey angelic behavior, e.g., doing good deeds.",
  },
    {id: 12,
      emoji:  "😐",
      name: "Neutral Face",
      meaning:"A yellow face with simple, open eyes and a flat, closed mouth. Intended to depict a neutral sentiment but often used to convey mild irritation and concern or a deadpan sense of humor.",
  },
    {id: 13,
      emoji:  "😴",
      name: "Sleeping Face",
      meaning:"A yellow face with eyes closed and mouth letting out three, cartoon-styled Zzzs overhead to indicate it's sound asleep. The Zzzs appear blue or purple across most platforms. May also represent boredom (slang, snooze)",
  },
   { id: 14,
     emoji:  "😶",
      name: "Face Without Mouth",
      meaning: "A yellow face with simple, open eyes and no mouth, as if at a loss for words. Meaning widely varies, but commonly conveys speechlessness, humility, and silence. May also convey moderately negative emotions, such as disappointment, frustration, or sadness.",
  },
   { id: 15,
     emoji:  "😏",
      name: "Smirking Face",
      meaning: "A yellow face with a sly, smug, mischievous, or suggestive facial expression. It features a half-smile, raised eyebrows, and eyes looking to the side. Often used to convey flirtation or sexual innuendo.",
},
    {id: 16,
      emoji: "👩",
      name: "Woman",
      meaning: "A woman of adult age. Differentiated from the girl emoji by the lack of pig-tails in her hair.",
  },
    {id: 17,
      emoji:  "👨",
      name: "Man",
      meaning: "A man of adult age, shown on some platforms with a moustache.",
  },

  { id: 18, 
    emoji:  "👶",
      name: "Baby",
      meaning:"The face of a young infant (baby). Shows the face of a baby with a small amount of hair on most platforms, while some variations show a pacifier (dummy) in its mouth. Android previously displayed this emoji as a swaddled baby.",
    },
   { id: 19,
     emoji:  "🧒",
      name: "Child",
      meaning:"A child with no gender specified. This may be used as a gender-inclusive alternative to the boy or girl emoji.",
    },
  { id: 20, 
    emoji:  "👦",
      name: "Boy",
      meaning:"The face of a boy, smiling. Previously differentiated from the man emoji on Android by wearing a cap, and on iOS by the lack of any facial hair.",
    },
   { id: 21,
     emoji: "👧",
      name: "Girl",
      meaning: "The face of a girl, smiling. Differentiated from the woman emoji by the hairstyle which features pigtails which are not present on the woman.",
    },

   { id: 22,
     emoji: "👴",
      name: "Old Man",
      meaning:"An elderly man gray (grey) hair, and visible wrinkles. Balding in many versions of this artwork, such as Apple and Microsoft designs.",
    },
   { id: 23,
     emoji:  "👵",
      name: "Old Woman",
      meaning: "An elderly woman with gray (grey) hair, and visible wrinkles. Wears glasses on some platforms.",
  },
    {id: 24,
      emoji:  "🤦",
      name: "Person Facepalming",
      meaning:"A hand shown pressing against the head of a person, commonly written as facepalm. Used to display frustration or embarrassment at the ineptitude of a person or situation.",
    },
  { id: 25, 
    emoji:  "🤷",
      name: "Person Shrugging",
      meaning: "A person shrugging their shoulders to indicate a lack of knowledge about a particular topic, or a lack of care about the result of a situation. Displays as raised shoulders, sometimes in conjunction with raised arms and flat hands. The shrug gesture in text (emoticon / kaomoji) form is known as a shruggie and typed as: ¯\\_(ツ)_/¯",
    },
    {id: 26,
      emoji:  "🙍",
      name: "Person Frowning",
      meaning:"An upset person, frowning with dismay. Gender is not specified, but generally shown as a woman.",
    },
  { id: 27, 
    emoji:  "🙎",
      name: "Person Pouting",
      meaning:"A person with a serious expression, showing mild displeasure with the situation. Could be considered to be reserved or stoic in response, as this person is not visible angry.",
    },
    {id: 28,
      emoji:  "🙆",
      name: "Person Gesturing OK",
      meaning:"A person with arms above her or his head, making an ‘OK’ sign (circle) with the whole body. No gender is specified, but this emoji is generally shown as a woman.",
    },
  { id: 29, 
    emoji:  "🙅",
      name: "Person Gesturing No",
      meaning:"A person with arms crossed forming an ‘X’ to indicate ‘no’ or ‘no good’. This motion is used on the TV game show Deal or No Deal to indicate ‘No Deal’. Intended to be gender-neutral but shown as a woman on most platforms.",
    },
   { id: 30,
     emoji:  "🎅",
      name: "Santa Claus",
      meaning:"Santa Claus, sometimes referred to as Father Christmas, brings joy to children at Christmas time. Displayed with a beard and red festive hat.",
    },

    {id: 31,
      emoji:  "🐱",
      name: "Cat Face",
      meaning:"Meow! A friendly, cartoon-styled face of a cat, looking straight ahead. Generally depicted as a yellowish-orange cat face with pointed ears and whiskers.",
    },
    {id: 32,
      emoji: "🙈",
      name: "See-No-Evil Monkey",
      meaning:"The see no evil monkey, called Mizaru (Japanese for “see not”), one of the Three Wise Monkeys. Depicted as the brown 🐵 Monkey Face with tan or pinkish hands covering its eyes.",
    },
    {id: 33,
      emoji:  "🙉",
      name: "Hear-No-Evil Monkey",
      meaning:"The hear no evil monkey, called Kikazaru (Japanese for “hear not”), one of the Three Wise Monkeys. Depicted as the brown 🐵 Monkey Face with tan or pinkish hands covering its ears.",
    },
  { id: 34, 
    emoji:  "🙊",
      name: "Speak-No-Evil Monkey",
      meaning:"The speak no evil monkey, called Iwazaru (Japanese for “say not”), one of the Three Wise Monkeys. Depicted as the brown 🐵 Monkey Face with its tan or pinkish hands covering its mouth.",
    },
   { id: 35,
     emoji:  "🐶",
      name: "Dog Face",
      meaning:"A friendly, cartoon-styled face of a dog, looking straight ahead. Depicted as the face of a dog of various breeds, generally light-brown and white, with pointed or floppy ears and its tongue hanging out.",
    },
    {id: 36,
      emoji:  "🐢",
      name: "Turtle",
      meaning:"A turtle, a slow-moving reptile with a shell. Depicted as a light-green turtle in full profile on all fours facing left, with a long neck and green, textured shell.",
    },
   { id: 37,
     emoji:  "🦄",
      name: "Unicorn",
      meaning:"The face of a unicorn, a mythical creature in the form of a white horse with a single, long horn on its forehead. In addition to the mythical unicorn, may be used to convey whimsy, fantasy, uniqueness, specialness, peace, and love. Often used for various content related to the LGBTQ community. Also often used in association with “unicorn” startups.",
    },
  { id: 38, 
    emoji:  "🐻",
      name: "Bear",
      meaning:"A friendly, cartoon-styled face of bear, looking straight ahead. Depicted as a brown bear with round ears and a tan muzzle. Resembles a teddy bear. Often used with an affectionate tone. Does not have a full-bodied bear emoji counterpart.",
    },
   { id: 39,
     emoji:  "🦋",
      name: "Butterfly",
      meaning:"A butterfly, a beautiful winged insect whose larva is a caterpillar. Depicted with its wings outspread, as a blue-and-black morpho butterfly or orange-and-black monarch butterfly.",
    },
   { id: 40,
     emoji:  "🐔",
      name: "Chicken",
      meaning:"A chicken, a bird used for its meat and eggs. Generally depicted as the white head of a chicken (hen or rooster) looking left, with a yellow beak, red comb on its head, and red wattle on its neck.",
    },
  { id: 41, 
    emoji:  "🦅",
      name: "Eagle",
      meaning:"A bald eagle, the majestic bird of prey with brown feathers and distinctive white head. Generally depicted facing left, with its wings outspread and talons out, as if swooping down to seize prey.",
    },
    {id: 42,
      emoji:  "🕊️",
      name:"Dove",
      meaning:"A dove carrying an olive branch, a symbol of peace in Western and Judeo-Christian culture. Depicted as a white bird in full profile facing left, flying as it holds a green sprig in its beak. Commonly used to represent such sentiments as peace, love, hope, and reconciliation.",
    },
    {id: 43,
      emoji:  "🦉",
      name: "Owl",
      meaning:"An owl, the hooting, large-eyed bird of the night. Depicted as a reddish-brown owl, as a great horned owl, facing forward, Shown with large, round, gold-rimmed eyes, feet curled on or as if on a branch, wings tucked in, and its distinctive, horn-like tufts of feathers. May be used to represent wisdom.",
    },
    {id: 44,
      emoji:  "🐬",
      name: "Dolphin",
      meaning:"A dolphin, a sleek marine mammal known to be social and intelligent. Generally depicted as a light-blue dolphin with a white belly in full profile facing left, its short snout curving down to a prominent dorsal fin and tail, as a bottlenose dolphin leaping in the air. May be used for various content concerning swimming, oceans, beaches, and summer fun.",
  },
    {id: 45,
      emoji:   "🦌",
      name: "Deer",
      meaning: "A deer, a fleet-footed, hoofed mammal whose males (bucks, stags) generally have antlers. Variously depicted as a light-brown deer in full profile on all fours facing left or as a deer face looking straight head; both depictions feature large, branched antlers. May be used to represent elk, moose, antelope, or reindeer, especially in connection with Christmas.",
  },
    {id: 46,
      emoji:  "🍀",
      name: "Four Leaf Clover",
      meaning: "A four-leaf clover, a symbol of good luck. Depicted as a bright green sprig of clover, with four, heart-shaped leaves.",
    },
    {id: 47,
      emoji:   "🌹",
      name:  "Rose",
      meaning: "A red rose. Depicted as a single, vertical red rose on a green stem. Commonly used for Valentine’s Day, Mother’s Day, and other special occasions. May be more generally used to express such sentiments as love and romance. Also used as a symbol of socialism or as a red accent color.",
    },
    {id: 48,
      emoji:  "🌻",
      name: "Sunflower",
      meaning:"A sunflower, a tall, round flower with large yellow petals. Depicted as a single, vertical sunflower with a large, dark-brown center on a green stem. Commonly used for Mother’s Day and other special occasions. May be more generally used to convey such sentiments happiness and love. Also used as a yellow accent color and in association with summer and farming.",
    },
    {id: 49,
      emoji:  "🌲",
      name:  "Evergreen Tree",
      meaning: "An evergreen tree, which keeps green leaves all year round. Depicted as a tall, dark green, cone-shaped tree with shaggy, layered leaves, as a pine or fir, showing a brown trunk.",
    },
   { id: 50,
     emoji:   "🌴",
      name: "Palm Tree",
      meaning:"A palm tree, a tree-like plant, as grows by the sea. Depicted as a palm tree with long, green, feather-like leaves and a tall, brown, segmented trunk. May be used to represent beaches, tropical climates and cultures, summer fun, and vacations (holidays). Vendors implement a similar tree in their 🏝️ Desert Island.",
    },
   { id: 51,
     emoji:   "🍁",
      name:  "Maple Leaf",
     meaning:"The distinctive, star-shaped leaf of the maple tree. Depicted as a reddish-orange maple leaf, as has changed color in the fall/autumn, with five pointed segments. Used as an emblem of Canada, featured on the 🇨🇦 Flag of Canada. Also used to represent trees and the season of fall/autumn more generally.",
   },
     { id: 52,
    emoji:  "🌙",
      name: "Crescent Moon",
      meaning:"A crescent moon, as in its waxing crescent phase. Depicts the moon as a thin, golden crescent, curving to the right and not displaying the remaining outline of the moon. May be used for the moon more generally and saying good night. May be used in association with ☪️ Star and Crescent, a popular but unofficial symbol of Islam.",
  },
   { id: 53,
     emoji:   "☀️",
      name: "Sun",
      meaning:"The sun, the star at the center of our solar system. Generally depicted as a golden-yellow disc radiating eight triangular rays, representing the sun’s heat and light. Commonly used to represent sunny, warm, or hot weather, light, heat, energy, life, outer space, astronomy, and various positive and happy (sunny) feelings.",
  },
    {id: 54,
      emoji:   "⭐",
      name: "Star",
      meaning:"A classic, five-point gold star. Commonly used for various metaphorical senses of star (e.g., for fame, success, excellence, reviews). Also used for emphasis or flair. Occasionally used for astronomical stars.",
    },
    {id: 55,
      emoji:  "❄️",
      name:  "Snowflake",
      meaning:"The unique, feathery ice crystal of a snowflake. Depicted as a bluish-white snowflake with six intricate symmetrical branches.",
  },
    {id: 56,
      emoji:  "🌈",
      name: "Rainbow",
      meaning:"The colorful arc of a rainbow, as may appear after rain. Generally depicted as the left half of a full rainbow, showing six bands of color: red, orange, yellow, green, blue, and violet. Commonly used to express gay pride. Also commonly used to convey various feelings of love and happiness. See also 🏳️‍🌈 Rainbow Flag.",
    },
    {id: 57,
      emoji:  "🔥",
      name: "Fire",
      meaning:"A flame, as produced when something is on fire. Depicted as a red, orange, and yellow flickering flame. Commonly used for various metaphorical expressions related to fire, including the slang hot (“attractive”) and lit (“excellent”).",
    },
    {id: 58,
      emoji:  "☁️",
      name: "Cloud",
      meaning:"A fluffy, white cloud, as a cumulus. May be used as a weather icon to represent a cloudy or overcast day.",
},
   { id: 59,
     emoji:  "⚡",
      name: "High Voltage",
      meaning:"A symbol for high voltage, as warns against injury from electricity. Depicted as a jagged yellow bolt. Commonly used to represent lightning, electricity, and various flashes. Also used to represent metaphorical energy and signal attention online.",
},
    {id: 60,
      emoji:  "🎄" ,
      name: "Christmas Tree",
      meaning:"A classic Christmas tree, an evergreen tree decorated with lights and ornaments to celebrate Christmas.  Depicted with round, variously colored ornaments and topped with a yellow star. Used for various content concerning the Christmas holiday and season as well as for wintertime more generally.",
  }
];

export default emotidex;